/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as BoardsRouteImport } from "./routes/boards";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ShareShareIdRouteImport } from "./routes/share.$shareId";
import { Route as CommunityBoardIdRouteImport } from "./routes/community.$boardId";
import { Route as BoardBoardIdRouteImport } from "./routes/board.$boardId";

const BoardsRoute = BoardsRouteImport.update({
  id: "/boards",
  path: "/boards",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: "/share/$shareId",
  path: "/share/$shareId",
  getParentRoute: () => rootRouteImport,
} as any);
const CommunityBoardIdRoute = CommunityBoardIdRouteImport.update({
  id: "/community/$boardId",
  path: "/community/$boardId",
  getParentRoute: () => rootRouteImport,
} as any);
const BoardBoardIdRoute = BoardBoardIdRouteImport.update({
  id: "/board/$boardId",
  path: "/board/$boardId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/boards": typeof BoardsRoute;
  "/board/$boardId": typeof BoardBoardIdRoute;
  "/community/$boardId": typeof CommunityBoardIdRoute;
  "/share/$shareId": typeof ShareShareIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/boards": typeof BoardsRoute;
  "/board/$boardId": typeof BoardBoardIdRoute;
  "/community/$boardId": typeof CommunityBoardIdRoute;
  "/share/$shareId": typeof ShareShareIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/boards": typeof BoardsRoute;
  "/board/$boardId": typeof BoardBoardIdRoute;
  "/community/$boardId": typeof CommunityBoardIdRoute;
  "/share/$shareId": typeof ShareShareIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/boards"
    | "/board/$boardId"
    | "/community/$boardId"
    | "/share/$shareId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/boards"
    | "/board/$boardId"
    | "/community/$boardId"
    | "/share/$shareId";
  id:
    | "__root__"
    | "/"
    | "/boards"
    | "/board/$boardId"
    | "/community/$boardId"
    | "/share/$shareId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BoardsRoute: typeof BoardsRoute;
  BoardBoardIdRoute: typeof BoardBoardIdRoute;
  CommunityBoardIdRoute: typeof CommunityBoardIdRoute;
  ShareShareIdRoute: typeof ShareShareIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/boards": {
      id: "/boards";
      path: "/boards";
      fullPath: "/boards";
      preLoaderRoute: typeof BoardsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/share/$shareId": {
      id: "/share/$shareId";
      path: "/share/$shareId";
      fullPath: "/share/$shareId";
      preLoaderRoute: typeof ShareShareIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/community/$boardId": {
      id: "/community/$boardId";
      path: "/community/$boardId";
      fullPath: "/community/$boardId";
      preLoaderRoute: typeof CommunityBoardIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/board/$boardId": {
      id: "/board/$boardId";
      path: "/board/$boardId";
      fullPath: "/board/$boardId";
      preLoaderRoute: typeof BoardBoardIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRoute,
  BoardBoardIdRoute: BoardBoardIdRoute,
  CommunityBoardIdRoute: CommunityBoardIdRoute,
  ShareShareIdRoute: ShareShareIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
