/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareShareIdRouteImport } from './routes/share.$shareId'
import { Route as JoinInviteCodeRouteImport } from './routes/join.$inviteCode'
import { Route as GroupCommunityIdRouteImport } from './routes/group.$communityId'
import { Route as CommunityBoardBoardIdRouteImport } from './routes/community-board.$boardId'
import { Route as BoardBoardIdRouteImport } from './routes/board.$boardId'

const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinInviteCodeRoute = JoinInviteCodeRouteImport.update({
  id: '/join/$inviteCode',
  path: '/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupCommunityIdRoute = GroupCommunityIdRouteImport.update({
  id: '/group/$communityId',
  path: '/group/$communityId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityBoardBoardIdRoute = CommunityBoardBoardIdRouteImport.update({
  id: '/community-board/$boardId',
  path: '/community-board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardIdRoute = BoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/community-board/$boardId': typeof CommunityBoardBoardIdRoute
  '/group/$communityId': typeof GroupCommunityIdRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/share/$shareId': typeof ShareShareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/community-board/$boardId': typeof CommunityBoardBoardIdRoute
  '/group/$communityId': typeof GroupCommunityIdRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/share/$shareId': typeof ShareShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/community-board/$boardId': typeof CommunityBoardBoardIdRoute
  '/group/$communityId': typeof GroupCommunityIdRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/share/$shareId': typeof ShareShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/board/$boardId'
    | '/community-board/$boardId'
    | '/group/$communityId'
    | '/join/$inviteCode'
    | '/share/$shareId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boards'
    | '/board/$boardId'
    | '/community-board/$boardId'
    | '/group/$communityId'
    | '/join/$inviteCode'
    | '/share/$shareId'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/board/$boardId'
    | '/community-board/$boardId'
    | '/group/$communityId'
    | '/join/$inviteCode'
    | '/share/$shareId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRoute
  BoardBoardIdRoute: typeof BoardBoardIdRoute
  CommunityBoardBoardIdRoute: typeof CommunityBoardBoardIdRoute
  GroupCommunityIdRoute: typeof GroupCommunityIdRoute
  JoinInviteCodeRoute: typeof JoinInviteCodeRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$inviteCode': {
      id: '/join/$inviteCode'
      path: '/join/$inviteCode'
      fullPath: '/join/$inviteCode'
      preLoaderRoute: typeof JoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$communityId': {
      id: '/group/$communityId'
      path: '/group/$communityId'
      fullPath: '/group/$communityId'
      preLoaderRoute: typeof GroupCommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-board/$boardId': {
      id: '/community-board/$boardId'
      path: '/community-board/$boardId'
      fullPath: '/community-board/$boardId'
      preLoaderRoute: typeof CommunityBoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRoute,
  BoardBoardIdRoute: BoardBoardIdRoute,
  CommunityBoardBoardIdRoute: CommunityBoardBoardIdRoute,
  GroupCommunityIdRoute: GroupCommunityIdRoute,
  JoinInviteCodeRoute: JoinInviteCodeRoute,
  ShareShareIdRoute: ShareShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
